### ISSUE TITLE
A fatal error in training

### ISSUE THREAD

**Issue by jonyzhang2023** [osudrl/RSS-2020-learning-memory-based-control#2]
Hi all, thanks for the great job in learning memory based control!
But I met this error when training ;

Traceback (most recent call last):
  File "main.py", line 92, in <module>
    run_experiment(args)
  File "/home/jony/github-repo/RSS-2020-learning-memory-based-control/algos/ppo.py", line 345, in run_experiment
    policy.train(0)
  File "/home/jony/anaconda3/envs/mujoco/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1836, in train
    raise ValueError("training mode is expected to be boolean")
ValueError: training mode is expected to be boolean

And I found that code:
`    policy.train(0)
    critic.train(0)`
in PPO.py, is something wrong with that?

**Comment by xicor7017** [comment]
This error is due to different PyTorch versions. Try replacing the above lines with the following: 
```
policy.train(False) critic.train(False)
```

**Comment by jonyzhang2023** [comment]
thanks for your reply!
I change it to 
`policy.train() 
critic.train()`
and it works.
